[tool.black]
line-length = 88
target_version = ['py311']
extend-exclude = '''
(
    /(
        \.eggs
        | \.git
        | \.mypy_cache
        | \.envs
        | \.venv
        | env
        | venv
        | build
    )/
)
'''

[tool.isort]
profile = "black"

[tool.flake8]
ignore = "E203, E501, W503"
max-line-length = 120
